Storyteller/Models/ErrorViewModel.cs
using System;

namespace Storyteller.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Storyteller/Models/PairingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Storyteller.Models
{
    public class PairingModel
    {
        public string ConnectionId { get; set; }
        public string Role { get; set; }
        public string Img { get; set; }
    }

}

Storyteller/ViewModels/AchievementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Storyteller.ViewModels
{
    public class AchievementViewModel
    {
        public string DisplayAchievement { get; set; }
    }
}

Storyteller/ViewModels/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Storyteller.ViewModels
{
    public class CategoryViewModel
    {
        public string Tag { get; set; }
        public int ScriptId { get; set; }
        public int ScriptCategoryId { get; set; }
        public string ScriptUrl { get; set; }
        public string ScriptName { get; set; }
        public int? ScriptMaxPlayer { get; set; }
        public string ScriptDuration { get; set; }
    }
}

Storyteller/ViewModels/GameRoomViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Storyteller.ViewModels
{
    public class GameRoomViewModel
    {
        public int ScriptId { get; set; }
        public string ScriptName { get; set; }
        public string CharacterImage { get; set; }
        public string CharacterName { get; set; }
        public string CharacterIntroduction { get; set; }
        public bool Choose { get; set; }
    }
}

Storyteller/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Storyteller.ViewModels
{
    public class HomeViewModel
    {
        public List<HomeScriptCategory> HomeScriptCategory { get; set; } //有哪些劇本分類 搞笑,愛情,恐怖......
        public List<NewScript> NewScripts { get; set; } //新的劇本
        public List<UserItems> TopUser { get; set; } //最受歡迎的使用者
        public List<BestScript> TopScript { get; set; } //創作出來的故事最受歡迎
    }

    public class HomeScriptCategory
    {
        public int ScriptCategoryId { get; set; }
        public int? CurrentOnlinePlayerCount { get; set; }
        public string ScriptCategoryUrl { get; set; }
    }

    public class NewScript
    {
        public int ScriptId { get; set; }
        public string ImgUrl { get; set; }
    }

    public class UserItems
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserImg { get; set; }
    }

    public class BestScript
    {
        public int BestCreationId { get; set; }
        public int ScriptId { get; set; }
        public string ScriptUrl { get; set; }
        public string UserId { get; set; }
        public string UserImg { get; set; }
        public int? CreationBeenLikedCount { get; set; }
    }
}

Storyteller/ViewModels/ScriptViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Storyteller.ViewModels
{
    public class ScriptViewModel
    {
        public int ScriptId { get; set; }
        public string ScriptUrl { get; set; }
        public string ScriptName { get; set; }
        public int? ScriptMaxPlayer { get; set; }
        public string ScriptDuration { get; set; }
        public string ScriptIntroduction { get; set; }
    }
}

Storyteller/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Storyteller.ViewModels
{
    public class UserViewModel
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserImg { get; set; }
    }
}

Storyteller/Controllers/ChatRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Storyteller.Controllers
{
    public class ChatRoomController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ChartRoom(string id)
        {
            return View();
        }
    }
}

Storyteller/Controllers/GameRoomController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Storyteller.Models;
using Storyteller.Services;

namespace Storyteller.Controllers
{
    public class GameRoomController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public readonly GameRoomService _gameRoomService;

        public GameRoomController(ILogger<HomeController> logger, GameRoomService gameRoomService)
        {
            _logger = logger;
            _gameRoomService = gameRoomService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("GameRoom/UserPairing/{ScriptID}")]
        public IActionResult UserPairing(string ScriptID)
        {
            var result = _gameRoomService.GetGameCharacter(ScriptID);
            ViewBag.ScriptJsonString = JsonConvert.SerializeObject(result);
            return View();
        }

        public IActionResult StoryRoom(string id)
        {
            ViewBag.test = id;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult CGTestRoom()
        {
            return View();
        }

        public IActionResult EndStoryRoom()
        {
            return View();
        }
    }
}

Storyteller/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
//using Storyteller.DBModels;
using Storyteller.Models;
using Storyteller.Services;
using Storyteller.ViewModels;

namespace Storyteller.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly HomeService _homeService;

        public HomeController(ILogger<HomeController> logger, HomeService homeService)
        {
            _logger = logger;
            _homeService = homeService;
        }

        public IActionResult Index()
        {
            var result = _homeService.GetHomeViewModel();
            return View(result);
        }

        [HttpPost]
        public IEnumerable<AchievementViewModel> Achievement(string UserID)
        {
            var result = _homeService.GetAchievement(UserID);
            return result;
        }


        [Route("Home/Category/{id}")]
        public IActionResult Category(string id)
        {
            var result = _homeService.GetCategoryScript(id);
            return View(result);
        }

        [Route("Home/ScriptDetail/{CategoryID}/{scriptID}")]
        public IActionResult ScriptDetail(string CategoryID, string scriptID)
        {
            var result = _homeService.GetScript(scriptID);
            return View(result);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public ActionResult SaveUserData(string jdata)
        {
            UserViewModel UVM = JsonConvert.DeserializeObject<UserViewModel>(jdata);
            _homeService.ViewToModel(UVM);
            return Ok();
        }
    }
}

Storyteller/Views/ChatRoom/ChartRoom.cshtml
@{
    ViewData["Title"] = "ChartRoom";
}

<header class="container-fluid containerheader chart-header">
    <div class="row">
        <div class="col-md-12 chart-title">
            <div class="c-title-icon">
                <i onclick="leaveRoom()" class="fas fa-sign-out-alt"></i>
            </div>
        </div>
    </div>
</header>

<section class="container chart-body">
    <div class="row">
        <div class="col chart-body-input">
            <div class="c-b-input-info">
                <div class="c-b-info-img">
                    <img src="~/img/StoryRoom_UserText/pngtree-meng-pet-cute-puppy-png-image_1845456.jpg" />
                </div>
                <div class="c-b-info-text">
                    <div class="c-b-i-text-name">
                        <h3>張雲雷</h3>
                        <button>查看故事結局</button>
                    </div>
                    <div class="c-b-i-text-btn">
                        <div class="cb-i-t-btnone text-center">
                            <div class="btnone-plus">
                                <i class="fas fa-user-plus"></i>
                            </div>
                            <h3>加為好友</h3>
                        </div>
                        <div class="cb-i-t-btntwo text-center">
                            <div class="btntwo-report">
                                <i class="fas fa-exclamation-triangle"></i>
                            </div>
                            <h3>檢舉</h3>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div class="c-b-input-people">
                <h3>與OOO開始聊天吧!</h3>
            </div>
            <div class="overflow-auto c-b-input-text">

                <button onclick="ShowLeaveModal()" class="btn btn-primary">別人離開聊天室Modal</button>
            </div>
        </div>
    </div>
</section>

<footer class="container-fluid containerfooter chart-footer">
    <div class="row">
        <div class="col chart-footer-input">
            <div class="c-f-input-img">
                <img src="~/img/StoryRoom_UserText/girl001 .jpg" />
            </div>
            <div class="c-f-input-text">
                <input type="text" placeholder="請輸入想和對方說的話..."/>
            </div>
            <div class="c-f-input-send">
                <i class="fas fa-paper-plane"></i>
            </div>
        </div>
    </div>
</footer>

<div id="chartModal" class="modal leaveroom-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content leaveRoom-content">
            <div class="modal-body leaveRoom-body">
                <p>確定要離開聊天室嗎?</p>
            </div>
            <div class="modal-footer leave-footer">
                <div class="leave-footer-btnone">
                    <p>離開</p>
                </div>
                <div class="leave-footer-btntwo" data-dismiss="modal">
                    <p>留下聊聊</p>
                </div>

            </div>
        </div>
    </div>
</div>

<div id="outherOneLeave" class="modal outherOneLeave-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content outherOneLeave-content">
            <div class="modal-body outherOneLeave-body">
                <p>對方已離開聊天室</p>
            </div>
        </div>
    </div>
</div>

@section topCSS {
    <link href="~/css/ChartRoom/StyleSheet_ChartRoom.css" rel="stylesheet" />
    <link href="~/css/InputFooter/StyleSheet_footer.css" rel="stylesheet" />
    <link href="~/css/StoryRoom/StyleSheet_UserText.css" rel="stylesheet" />
    <link href="~/css/StoryRoom/StyleSheet_UserTextRight.css" rel="stylesheet" />
    <link href="~/css/ChartRoom/StyleSheet_LeaveRoomModal.css" rel="stylesheet" />
    <link href="~/css/ChartRoom/StyleSheet_OutherLeaveModal.css" rel="stylesheet" />
    <link href="~/css/StoryRoom/StyleSheet_Choose.css" rel="stylesheet" />
}

@section endJs {
    <script src="~/js/ChatRoom/StoryRoom_UserText.js"></script>
    <script src="~/js/ChartRoom/ChartRoom_LeaveRoomModal.js"></script>
}

Storyteller/Views/GameRoom/CGTestRoom.cshtml
<partial name="_HearderPartial" />


<section class="container">
    <div class="row">
        <div class="col-md-12">
            <partial name="_CGModel" />
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
           <partial name="_AuthorModel" />
        </div>
    </div>
</section>


<partial name="_InputFooterPartial" />









@section topCSS
{
    <link href="~/css/InputFooter/StyleSheet_footer.css" rel="stylesheet" />
    <link href="~/css/Hearder/StyleSheet_hearder.css" rel="stylesheet" />
    <link href="~/css/StoryRoomCG/StoryCGModle.css" rel="stylesheet" />
    <link href="~/css/StoryRoomCG/AuthorModel.css" rel="stylesheet" />
}

Storyteller/Views/GameRoom/EndStoryRoom.cshtml
<partial name="_HearderPartial" />


<section class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="CGImg">
                <div class="CGModelUserLeft">
                </div>
                <img class="d-block w-100" v-bind:src="items.CG_img" />
                <div class="CGModelUserRight">
                </div>
                <div class="AddFriend">
                    。。。
                </div>
            </div>
        </div>
    </div>

    <div class="row GamePadding">
        <div class="GameText">
            <div class="GameTextTitle">
                <h1>支線結局名稱</h1>
            </div>
            <div class="GameTextTag">
                <p>38%的人答成此結局</p>
            </div>
            <div class="GameTextContent">
                <p>
                    我是結尾劇情內容我是結尾劇情內容我是結尾劇情內容
                    我是結尾劇情內容我是結尾劇情內容我是結尾劇情內容
                    我是結尾劇情內容我是結尾劇情內容我是結尾劇情內容
                    我是結尾劇情內容我是結尾劇情內容我是結尾劇情內容
                    我是結尾劇情內容我是結尾劇情內容我是結尾劇情內容
                    我是結尾劇情內容我是結尾劇情內容我是結尾劇情內容
                </p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <partial name="_AuthorModel" />
        </div>
    </div>

    <div class="row GameButtonJustify">
        <div class="GameButton">
            <a href="#">
                <div class="GameBtn">
                    <p>離開</p>
                </div>
            </a>

            <a href="#">
                <div class="GameBtn">
                    <p>繼續聊聊</p>
                </div>
            </a>
        </div>
    </div>
</section>


<partial name="_InputFooterPartial" />


@section topCSS
{
    <link href="~/css/InputFooter/StyleSheet_footer.css" rel="stylesheet" />
    <link href="~/css/Hearder/StyleSheet_hearder.css" rel="stylesheet" />
    <link href="~/css/StoryRoomCG/StoryCGModle.css" rel="stylesheet" />
    <link href="~/css/StoryRoomCG/AuthorModel.css" rel="stylesheet" />
    <link href="~/css/EndStoryRoom/EndStoryRoom.css" rel="stylesheet" />
}

Storyteller/Views/GameRoom/UserPairing.cshtml
<header class="container-fluid containerheader">
    <div class="row">
        <div class="col-md-12 herderBox">
            <div id="Go_Back" class="btn-left">
                <i class="fas fa-angle-left"></i>
            </div>
            <div id="Title_Name" class="txt-title">{{items.title}}</div>
            <div class="btn-right">
                <i class="fas fa-cog"></i>
            </div>
        </div>
    </div>
</header>
<section class="container" id="rolesDataChoose">
    <div class="row roleData">
        <div class="col my-2">
            <div class="text-center" id="rolesChoose">
                <div class="btn-choose border-0" id="prev" type="button" onclick="ChangeRole('-1')">
                    <i class="fas fa-chevron-left"></i>
                </div>

                <div class="pic-role mx-auto">
                    <img v-bind:src="items.CharacterImage" alt="Alternate Text" class="d-block h-100" />
                </div>

                <div class="btn-choose border-0" id="next" type="button" onclick="ChangeRole('+1')">
                    <i class="fas fa-chevron-right"></i>
                </div>

            </div>
        </div>
    </div>

    <div class="row" id="pic-success" style="display: none;">
        <div class="col-6 my-2">
            <div id="rolesChoose">
                <div class="pic-role ml-auto mappingRole">
                    <img v-bind:src="items.CharacterImage" alt="Alternate Text" class="d-block h-100" />
                </div>
            </div>
        </div>
        <div class="col-6 my-2">
            <div id="rolesChoose">
                <div class="pic-role mr-auto mappingRole">
                    <img src="#" alt="Alternate Text" class="d-block h-100" id="otherRoleimg" />
                </div>
            </div>
        </div>
    </div>

    <div class="row roleData">
        <div v-if="!items.Choose" class="col my-5">
            <div class="rolesInfo">
                <div class="rolesName">
                    <h3>{{items.CharacterName}}</h3>
                </div>
                <div class="rolesDesc">
                    <p>{{items.CharacterIntroduction}}</p>
                </div>
            </div>
        </div>
        <div v-else class="col my-2 text-center">
            <div class="pair-warp">
                <div class="wavy">
                    <span style="--i:1;">配</span>
                    <span style="--i:2;">對</span>
                    <span style="--i:4;">搜</span>
                    <span style="--i:3;">索</span>
                    <span style="--i:5;">中</span>
                    <span style="--i:6;">.</span>
                    <span style="--i:7;">.</span>
                    <span style="--i:8;">.</span>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="display: none;" id="text-success">
        <div class="col my-2 text-center">
            <div class="pair-success">
                <div class="success">
                    <span>配</span>
                    <span>對</span>
                    <span>成</span>
                    <span>功</span>
                </div>
            </div>
        </div>
    </div>

    <div class="row btn-row">
        <div class="col mt-5 d-flex justify-content-center">
            <div class="btn-div">
                <button type="button" id="btn-pair" @@click="Gopair">確認</button>
            </div>
        </div>
    </div>
</section>

@section topCSS{
    <link href="~/css/Hearder/StyleSheet_hearder.css" rel="stylesheet" />
    <link href="~/css/UserPairing/StyleSheet_UserPairing.css" rel="stylesheet" />
}

@section endJS{
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script>
        var otherUser = [];
        let role = '';
        let imgR = '';
        let tickTime = 0;
        var connection;
        var waittingTimes;
        var vm, hearderVm;


        var rolesData = @Html.Raw(ViewBag.ScriptJsonString);


        $(document).ready(function () {
            Binding();

            @* 畫面ready好後開始連線至hub *@
            connection = new signalR.HubConnectionBuilder().withUrl("/RoomHub").build();
            connection.start().then(function () {
                console.log('SignalR connection succeeded');

            }).catch(function (err) {
                return console.error(err.toString());
            });

            connection.on("CreateRole", function (roleListe) {
                console.log('有一位玩家加入配對');
                otherUser.push(JSON.parse(roleListe));
                console.log(roleListe);

            });

            connection.on("RemoveRole", function (roleListe) {
                console.log('有一位玩家離開配對');
                otherUser.push(JSON.parse(roleListe));
                console.log(roleListe);
            });

            connection.on("Leave", function (connectionId) {
                console.log(`${connectionId}玩家離開連線`);
            });

            connection.on("PairingSuccess", function (roleValue,img,roomid) {
                console.log('PairingSuccess ok')
                localStorage.setItem('data', roleValue);
                localStorage.setItem(roleValue, rolesData[0].ScriptName);
                $('#otherRoleimg').attr('src', img);
                $('.roleData').hide();
                $('.btn-row').hide();
                $('#pic-success').show();
                $('#text-success').show();
                setTimeout(function () {
                    document.location.href = `/GameRoom/StoryRoom/${roomid}`;
                }, 3000);
            });
        });

        function UpdateRoomData(role, imgR) {
            console.log('Pairing go')
            connection.invoke("Pairing", role, imgR).catch(function (err) {
                return console.error(err.toString());
            });

            tickTime++;
            if (tickTime > 5) {
                clearInterval(waittingTimes);
                alert('沒有相對的角色');
            }
        }

        function Binding() {
            vm = new Vue({
                el: '#rolesDataChoose',
                data: { items: rolesData[0] },
                methods: {
                    Gopair: function () {
                        @* 按下確認 *@
                        imgR = vm.$data.items.CharacterImage;
                        role = vm.$data.items.CharacterName;

                        vm.$data.items.Choose = !vm.$data.items.Choose;
                        if (vm.$data.items.Choose) {
                            $('#btn-pair').css("background", "var(--bgGray)").text("取消");
                            $('.btn-choose').hide();
                            connection.invoke("CreateRole", role, imgR).catch(function (err) {
                                return console.error(err.toString());
                            });

                            waittingTimes = setInterval(function () { UpdateRoomData(role, imgR) }, 3000);
                        }
                        else {
                            clearInterval(waittingTimes);
                            $('#btn-pair').css("background", "var(--mainColor)").text("確認");
                            $('.btn-choose').show();
                            connection.invoke("RemoveRole").catch(function (err) {
                                return console.error(err.toString());
                            });//要移除自己

                        }
                    }
                }
            });

            hearderVm = new Vue({
                el: '#Title_Name',
                data: { items: { "title": rolesData[0].ScriptName } }
            })
        }

        function GetCurrentBindingData() {
            return vm.$data.items;
        }
        function ShowData(data) {
            vm.$data.items = data;
        }
        function ChangeRole(no) {
            var tmp = GetCurrentBindingData();
            var i = rolesData.indexOf(tmp);
            var _index = eval(i + no);
            if (_index >= 0 && _index <= (rolesData.length - 1)) {
                ShowData(rolesData[_index]);
            }
        }
    </script>
}

Storyteller/Views/Home/Index.cshtml
@model Storyteller.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

@section topCSS{
    <link href="~/css/HomePage.css" rel="stylesheet" />
    <link href="~/css/Hearder/StyleSheet_hearder.css" rel="stylesheet" />
}

<partial name="_HearderPartial" />

<div class="container" id="userInfo">
    <div class="row">
        <div class="col-8">
            <h5>
                哈囉，{{UserName}}
                <span style="display: inline; color: #70CDB8;">></span>
                    <span id="AchievementName" class="badge badge-info"></span>
            </h5>
        </div>
        <div class="col-4">
            <img v-bind:src="UserImg" alt="">
        </div>
    </div>
    <div class="row" id="btnrow">
        <div class="col">
            <button type="button" class="btn">
                <div class="btn-div">
                    <i class="far fa-star"></i>
                </div>
                <span>作品</span>
            </button>
            <button type="button" class="btn">
                <div class="btn-div">
                    <i class="fas fa-crown"></i>
                </div>
                <span>成就</span>
            </button>
            <button type="button" class="btn">
                <div class="btn-div">
                    <i class="fas fa-pencil-alt"></i>
                </div>
                <span>創作</span>
            </button>
        </div>
    </div>
</div>

<div class="container" id="script">
    <div class="row">
        <div class="col">
            <!-- Swiper -->
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    @foreach (var item in Model.HomeScriptCategory)
                    {
                        <div class="swiper-slide">
                            <img src="@item.ScriptCategoryUrl" alt="Alternate Text" id="@item.ScriptCategoryId"/>
                            @if (item.ScriptCategoryId == 0)
                            {
                                <span class="sp" id="@item.ScriptCategoryId">戀愛</span>
                            }
                            else if (item.ScriptCategoryId == 1)
                            {
                                <span class="sp" id="@item.ScriptCategoryId">搞笑</span>
                            }
                            else if (item.ScriptCategoryId == 2)
                            {
                                <span class="sp" id="@item.ScriptCategoryId">恐怖</span>
                            }
                        </div>
                    }
                </div>
                <!-- Add Pagination -->
                <div class="swiper-pagination"></div>
            </div>
        </div>
    </div>
</div>

<div class="container" id="newScript">
    <div class="row">
        <div class="col">
            <h5>新劇本上架！</h5>
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active" style="background-color: #70CDB8;"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1" style="background-color: #70CDB8;"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2" style="background-color: #70CDB8;"></li>
                </ol>
                <div class="carousel-inner">
                    @foreach (var item in Model.NewScripts)
                    {
                        <div class="carousel-item active">
                            <img src="@item.ImgUrl" class="d-block w-100" alt="...">
                        </div>
                    }
                    @*<div class="carousel-item active">
                            <img src="./beanfun2.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="./beanfun2.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="./beanfun3.jpg" class="d-block w-100" alt="...">
                        </div>*@
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="container" id="top10Player">
    <div class="row">
        <div class="col-8">
            <h5>本周Top 10玩家</h5>
        </div>
        <div class="col-4">
            <!-- <span>名人榜 ></span> -->
            <a href="">名人榜 ></a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <!-- Swiper -->
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    @foreach (var item in Model.TopUser)
                    {
                        <div class="swiper-slide">
                            <img src="@item.UserImg" alt="Alternate Text" />
                            <span>@item.UserName</span>
                        </div>
                    }
                </div>
                <!-- Add Pagination -->
                <!-- <div class="swiper-pagination"></div> -->
            </div>
        </div>
    </div>
</div>

<div class="container" id="top10Creation">
    <div class="row">
        <div class="col-8">
            <h5>本周Top 10創作</h5>
        </div>
        <div class="col-4">
            <!-- <span>展館 ></span> -->
            <a href="">展館 ></a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <!-- Swiper -->
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    @foreach (var item in Model.TopScript)
                    {
                        <div class="swiper-slide">
                            <img src="@item.ScriptUrl" alt="Alternate Text" />
                            <span><i class="fas fa-heart"></i> @item.CreationBeenLikedCount</span>
                        </div>
                    }
                </div>
                <!-- Add Pagination -->
                <!-- <div class="swiper-pagination"></div> -->
            </div>
        </div>
    </div>
</div>

<div class="container-fluid containerfooter" id="indexFooter">
    <div class="row">
        <div class="col">
            @*<a asp-controller="GameRoom" asp-action="UserPairing">*@
                <i class="fas fa-angle-double-up"></i>
                <span>Top</span>
            @*</a>*@
        </div>
    </div>
</div>

@section endJS{
    <!-- Swiper JS -->
    <script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="~/js/HomePage/HomePage.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://beangostg.blob.core.windows.net/beango-static-stg/sdk/beango_stg.min.js"></script>
    <script src="~/js/BeanfunSDK/BeanfunSDK.js"></script>
}

Storyteller/Views/Shared/_AuthorModel.cshtml
<div class="AuthorArea">
    <div class="col-4 AuthorImg">
        <img src="https://picsum.photos/400/400/?random=15">
    </div>

    <div class="col-8 AuthorRight">
        <div class="AuthorText">
            <h3>作者名</h3>
            <p>短介紹短介紹短介紹短介紹短介紹短介紹短介紹</p>
        </div>

        <div class="AuthorButton">
            <a href="#">
                <div class="AuthorBtn">
                    LIKE!
                </div>
            </a>
            <a href="#">
                <div class="AuthorBtn">
                    他的劇本
                </div>
            </a>
        </div>
    </div>
</div>

Storyteller/Views/Shared/_CGModel.cshtml
<div class="CGImg">
    <img class="d-block w-100" v-bind:src="items.CGImg"/>
</div>